[pytest]
testpaths =
    api-tests/tests
    ui-tests/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: быстрые критичные проверки
    regression: расширенная регрессионная проверка
