[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --tracing=retain-on-failure
    --video=retain-on-failure
    --screenshot=only-on-failure
    --output=artifacts

markers =
    smoke: быстрые критичные проверки UI
    regression: расширенная регрессионная проверка UI
